version: '3.8'

services:
  app:
    container_name: chromatices/stockelper:1.2
    build: .
    ports:
      - "30001:8000"
    volumes:
      - db-data:/code/db-data
    environment:
      - PIPENV_VENV_IN_PROJECT=1

volumes:
  db-data:
