version: '3.8'

services:
  app:
    image: "chromatices/stockelper:1.${MINOR}"
    build: .
    ports:
      - "30001:8000"
    volumes:
      - db-data:/code/db-data
    environment:
      - PIPENV_VENV_IN_PROJECT=1

volumes:
  db-data:
